In [3]:
import numpy as np

arr= np.array([1, 2, 3])
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr[0], arr[1], arr[2])
arr[2]=4
print(arr)

# create rank 2 array
arr2= np.array([[1, 2, 3], [4, 5, 6]])
print(arr2.shape)
print(arr2[0, 0], arr2[0, 1], arr2[1, 0])
print(arr2[-1])

<class 'numpy.ndarray'>
int64
(3,)
1 2 3
[1 2 4]
(2, 3)
1 2 4
[4 5 6]


In [10]:
zero = np.zeros((2,2))
print(zero)

one = np.ones((1, 2))
print(one)

constant = np.full((2, 2), 5)
print(constant)

diag = np.eye(3)
print(diag)

diag = np.eye(4, k=1)
print(diag)

rand=np.random.random((2, 2))
print(rand)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[5 5]
 [5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
[[0.91536567 0.98917935]
 [0.39829294 0.81828931]]


In [12]:
arr = np.arange(10)
print(arr[0:8:2])

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr[:2, :2])

[0 2 4 6]
[[1 2]
 [5 6]]


In [13]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr[[0, 1, 2], [0, 1, 1]])

[1 4 6]
