In [2]:
import numpy as np
import pandas as pd

In [5]:
tans = pd.DataFrame({"A": [12, 4, 5, None, 1],
                    "B": [7, 12, 54, 3, None],
                    "C": [20, 16, 11, 3, 8],
                   "D":[14, 3, None, 2, 6]},
                    index= ['Row_1', 'Row_2', 'Row_3', 'Row_4', 'Row_5'])

In [6]:
tans

A     B   C     D
Row_1  12.0   7.0  20  14.0
Row_2   4.0  12.0  16   3.0
Row_3   5.0  54.0  11   NaN
Row_4   NaN   3.0   3   2.0
Row_5   1.0   NaN   8   6.0

In [7]:
result= tans.transform(lambda x : x +10)

In [8]:
result

A     B   C     D
Row_1  22.0  17.0  30  24.0
Row_2  14.0  22.0  26  13.0
Row_3  15.0  64.0  21   NaN
Row_4   NaN  13.0  13  12.0
Row_5  11.0   NaN  18  16.0

In [9]:
NaN + 10

NameError: name 'NaN' is not defined

In [10]:
x = np.random.randint(10, 200, size=10)

In [13]:
x

array([199, 159, 146,  94,  60, 197, 107,  27,  67,  40])

In [14]:
np.digitize(x, bins=[50])

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 0])

In [16]:
np.digitize(x, bins=[50, 100])

array([2, 2, 2, 1, 1, 2, 2, 0, 1, 0])

In [17]:
df=pd.DataFrame({"height":x})

In [18]:
df

height
0     199
1     159
2     146
3      94
4      60
5     197
6     107
7      27
8      67
9      40

In [20]:
df['binned']=pd.cut(x=df['height'], bins=[0, 25, 50, 100, 200])

In [21]:
df

height      binned
0     199  (100, 200]
1     159  (100, 200]
2     146  (100, 200]
3      94   (50, 100]
4      60   (50, 100]
5     197  (100, 200]
6     107  (100, 200]
7      27    (25, 50]
8      67   (50, 100]
9      40    (25, 50]

In [22]:
df['bind_label']=pd.cut(x=df['height'],
                       bins=[0, 25, 50, 100, 200],
                       labels=[1, 2,3, 4])

In [23]:
df

height      binned bind_label
0     199  (100, 200]          4
1     159  (100, 200]          4
2     146  (100, 200]          4
3      94   (50, 100]          3
4      60   (50, 100]          3
5     197  (100, 200]          4
6     107  (100, 200]          4
7      27    (25, 50]          2
8      67   (50, 100]          3
9      40    (25, 50]          2

In [24]:
pd.qcut(df['height'], q=5)

0    (166.6, 199.0]
1    (122.6, 166.6]
2    (122.6, 166.6]
3     (83.2, 122.6]
4      (56.0, 83.2]
5    (166.6, 199.0]
6     (83.2, 122.6]
7    (26.999, 56.0]
8      (56.0, 83.2]
9    (26.999, 56.0]
Name: height, dtype: category
Categories (5, interval[float64]): [(26.999, 56.0] < (56.0, 83.2] < (83.2, 122.6] < (122.6, 166.6] < (166.6, 199.0]]

In [27]:
degrees= ['none', 'cum laude', 'magna cum laude', 'summa cum laude']
student_results= [3, 93, 3.24, 2.80, 2.83, 3.91, 3.698, 3.731, 3.25, 3.24, 2.82, 3.22]
student_results.sort(reverse=True)

student_results_degrees= pd.cut(student_results, [0, 3.6, 3.8, 3.9, 4.0], labels=degrees)
honor= pd.DataFrame({'grades': student_results, 
                    'honors': student_results_degrees})

In [28]:
honor


grades           honors
0   93.000              NaN
1    3.910  summa cum laude
2    3.731        cum laude
3    3.698        cum laude
4    3.250             none
5    3.240             none
6    3.240             none
7    3.220             none
8    3.000             none
9    2.830             none
10   2.820             none
11   2.800             none

In [30]:
pd.value_counts(student_results_degrees).

none               8
cum laude          2
summa cum laude    1
magna cum laude    0
dtype: int64